### PR TITLE
fix: add text-overflow to suggestion list items

### PR DESCRIPTION
**Pull request by arnautov-anton**
### 🎯 Goal

Add text-overflow rule to the text of suggestion list items.

### 🎨 UI Changes

image

### CODE REVIEW

**Comment by szuperaz** [comment]
We have utility classes for this: https://github.com/GetStream/stream-chat-css/blob/theming2/src/v2/styles/_utils.scss#L20 (for parent and child element) - these utility classes help with the fact that different platforms use different default fonts, and the letters inside those fonts sometimes can overflow, and the utility class helps displaying those letters correctly

**Comment by arnautov-anton** [comment]
> We have utility classes for this: https://github.com/GetStream/stream-chat-css/blob/theming2/src/v2/styles/_utils.scss#L20 (for parent and child element) - these utility classes help with the fact that different platforms use different default fonts, and the letters inside those fonts sometimes can overflow, and the utility class helps displaying those letters correctly. In this case it probably doesn't matter, but it's probably safe to use the utility class anyways.

Good point, thanks, fixing now. :)

**Review by szuperaz — APPROVED** [review]

**Pull request merged**
